# standard jekyll configuration

permalink: /:title/
pygments: false
exclude: ['Rakefile', 'README.md', 'config.rb', "Gemfile", "Gemfile.lock", "Procfile", "config.ru", "unicorn.rb", "vendor"]
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# configuration required for some pages

domain: dotbootstrap
title: .bootstrap - safe with most medications
author: .bootstrap
email: dotbootstrap@x2q.net

# configuration for ehancements, uncomment to enable

#feedburner:
#  id: feedburnerid

google_analytics:
   account: UA-120957-20

github:
  username: x2q

disqus:
  id: dotbootstrap
