# standard jekyll configuration

permalink: /:title/
pygments: false
paginate: 20
exclude: ['Rakefile', 'README.md', 'config.rb', "Gemfile", "Gemfile.lock", "Procfile", "config.ru", "unicorn.rb", "vendor"]
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# configuration required for some pages

domain: dotbootstrap.x2q.net
title: .bootstrap - safe with most medications
author: .bootstrap
email: dotbootstrap@x2q.net

# configuration for ehancements, uncomment to enable

#feedburner:
#  id: feedburnerid

google_analytics:
   account: UA-120957-20

github:
  username: x2q

disqus:
  id: exblogx2qnet

jekyll-press:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
